apiVersion: v1

kind: Service

metadata:

  name: mywebservice

  labels:

    run: mywebservice

spec:

  type: NodePort

  ports:

  - port: 80

    protocol: TCP

    name: http

  selector:

    app: mywebservice
